name: Publish on NPM
on:
  push:
    branches: [main]
  repository_dispatch:
    types: [publish]
env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.32.11
      - name: Install dependencies
        run: pnpm i
      - name: Run publish script
        run: pnpm release
